"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import backdrop from "../../../public/brand/backdrop.jpg";

/** How much the image grows across a full page scroll. Deliberately small - the
 *  effect should register as depth, not as a zoom. */
const MAX_SCALE = 0.22;
/** Slight upward drift, so the peak settles as you descend the page. */
const MAX_DRIFT = 2.5; // percent

/**
 * Scroll-linked zoom on the backdrop image.
 *
 * The image scales from 1 to 1.22 across the document, easing the parallax the
 * same way a long camera push would. Written straight to `style.transform` from
 * a rAF loop - no React state per scroll event, so it stays off the render path.
 *
 * The image itself is generated by `scripts/generate-backdrop.py`, so it is
 * original work with no stock licence attached.
 */
export default function ScrollZoomBackdrop() {
  const ref = useRef<HTMLDivElement>(null);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    let raf = 0;
    let queued = false;
    let current = 0;
    let target = 0;

    const readScroll = () => {
      const max = document.documentElement.scrollHeight - window.innerHeight;
      target = max > 0 ? Math.min(window.scrollY / max, 1) : 0;
      queued = false;
    };

    const frame = () => {
      // Ease toward the scroll position so fast flicks do not snap the image.
      current += (target - current) * 0.08;
      const scale = 1 + current * MAX_SCALE;
      const drift = -current * MAX_DRIFT;
      el.style.transform = `scale(${scale.toFixed(4)}) translateY(${drift.toFixed(3)}%)`;
      raf = requestAnimationFrame(frame);
    };

    const onScroll = () => {
      if (queued) return;
      queued = true;
      requestAnimationFrame(readScroll);
    };

    readScroll();
    current = target;
    raf = requestAnimationFrame(frame);
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll, { passive: true });

    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
    };
  }, []);

  return (
    <>
      <div
        ref={ref}
        aria-hidden="true"
        className="absolute inset-0 will-change-transform"
        style={{ transformOrigin: "58% 62%" }}
      >
        <Image
          src={backdrop}
          alt=""
          fill
          quality={82}
          sizes="100vw"
          placeholder="blur"
          onLoad={() => setLoaded(true)}
          className={`object-cover transition-opacity duration-1000 ${
            loaded ? "opacity-[0.42]" : "opacity-0"
          }`}
        />
      </div>

      {/* Contrast scrim. Measured: over the brightest 0.1% of the backdrop this
          lifts ash-300 body text from 4.31:1 (under AA) to 5.83:1. Do not
          remove it without re-measuring. */}
      <div
        aria-hidden="true"
        className="absolute inset-0"
        style={{ background: "rgba(4,7,14,0.18)" }}
      />
    </>
  );
}
